# Generated by Django 4.0.3 on 2022-10-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256)),
                ('editor', models.CharField(max_length=256)),
                ('editor1', models.CharField(max_length=256)),
                ('file01', models.CharField(max_length=256)),
                ('type', models.CharField(max_length=256)),
                ('aname', models.CharField(max_length=256)),
            ],
        ),
    ]
