# Generated by Django 4.0.3 on 2022-10-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='file01',
            field=models.FileField(max_length=256, upload_to=''),
        ),
    ]
